### ISSUE TITLE
Theory behind pose backprop

### ISSUE THREAD

**Issue by VladimirYugay** [kuldeepbrd1/diff-3dgs-cam-grad#2]
Can you please elaborate on the gradient computation starting [here](https://github.com/kuldeepbrd1/diff-3dgs-cam-grad/blob/10a9b10f58f41e430f0682c21b5ae3d18585ab3f/cuda_rasterizer/backward.cu#L293)? 

While this makes sense:
```
// dL/dW = dL/dT *dT/dW
// T = W * J
// dL/dW = J^T * dL/dT
```

You mentioned this [paper](https://arxiv.org/pdf/2312.06741.pdf), and there it seems that `dW/dTcw` is a `9x6` matrix, and I'm not sure how should it match `dl/dW` of shape (3x3) that you get. 

Also, shouldn't dl_dw look like this?

```
float dL_dW00 = J[0][0] * dL_dT00 + J[1][0] * dL_dT10;
float dl_dW01 = J[0][0] * dL_dT01 + J[1][0] * dL_dT11;
float dl_dW02 = J[0][0] * dL_dT02 + J[1][0] * dL_dT12;
float dl_dW10 = J[0][1] * dL_dT00 + J[1][1] * dL_dT10;
float dl_dW11 = J[0][1] * dL_dT01 + J[1][1] * dL_dT11;
float dl_dW12 = J[0][1] * dL_dT02 + J[1][1] * dL_dT12;
float dl_dW20 = J[0][2] * dL_dT00 + J[1][2] * dL_dT10;
float dl_dW21 = J[0][2] * dL_dT01 + J[1][2] * dL_dT11;
float dl_dW22 = J[0][2] * dL_dT02 + J[1][2] * dL_dT12;
```

**Comment by kuldeepbrd1** [comment]
Hi @VladimirYugay 

Apologies for the late response. I see you have closed the issue, so I hope it is resolved. But I'll add a comment here for reference anyway.

The `T` in `dL_dT that you mention` is just an intermediate variable `T=W*J` from the original 3DGS implementation. 
This might create confusion with the pose transform. But in my implementation, the pose transformation is denoted as `T_cw` and the gradients with respect to the loss are given as `dL_dTcw` as [here](https://github.com/kuldeepbrd1/diff-3dgs-cam-grad/blob/10a9b10f58f41e430f0682c21b5ae3d18585ab3f/cuda_rasterizer/backward.cu#L328).

For this, we backpropagate gradients to `J` and `W` as:
$$\partial \mathcal{L} = \langle \frac{\partial \mathcal{L}}{\partial T}, (\partial J ) W \rangle + \langle \frac{\partial \mathcal{L}}{\partial T}, J\partial W \rangle $$ 

So, the gradients w.r.t these become:

$$ \frac{\partial \mathcal{L}}{\partial J} = \frac{\partial \mathcal{L}}{\partial T}  W^T $$ 

$$ \frac{\partial \mathcal{L}}{\partial W} = J^T\frac{\partial \mathcal{L}}{\partial T}  $$

Note that $J$ is the upper 2x3 matrix of the jacobian of the perspective transform at a camera coordinate as explained in this [paper](https://www.cs.umd.edu/~zwicker/publications/EWASplatting-TVCG02.pdf). 

Otherwise, the code snippet you mentioned is exactly as [here](https://github.com/kuldeepbrd1/diff-3dgs-cam-grad/blob/10a9b10f58f41e430f0682c21b5ae3d18585ab3f/cuda_rasterizer/backward.cu#L297).

However, I might have messed up transpose operations somewhere. That primarily comes from inconsistency between the equation 31 in this [paper](https://www.cs.umd.edu/~zwicker/publications/EWASplatting-TVCG02.pdf) and the use of $T=WJ$ in 3DGS implementation. I haven't had the time to sit down and double-check this yet.
